# Dockerfile-mariadb

FROM fedora:latest
RUN echo "proxy=http://10.0.0.2:3128" >> /etc/dnf/dnf.conf
RUN dnf update -y && dnf install mc procps-ng net-tools iproute iputils mariadb-server -y
RUN mysql_install_db --user=mysql --ldata=/var/lib/mysql
RUN mkdir -p /var/lib/mysql && chown -R mysql:mysql /var/lib/mysql
ENV MYSQL_ROOT_PASSWORD= \
    MYSQL_DATABASE=
RUN mkdir -p /shared
EXPOSE 3306
COPY docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["mysqld_safe"]